# Generated by Django 3.2.13 on 2023-08-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_brokerage_account_id', models.CharField(max_length=20)),
                ('brokerage', models.CharField(max_length=20)),
                ('listing_exchange', models.CharField(max_length=20)),
                ('asset_class', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=10)),
                ('brokerage_order_id', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField()),
                ('time_zone', models.CharField(max_length=5)),
                ('buy_sell', models.CharField(max_length=5)),
                ('open_close', models.CharField(max_length=1)),
                ('quantity', models.FloatField()),
                ('currency_primary', models.CharField(max_length=5)),
                ('order_price', models.FloatField()),
                ('order_money', models.FloatField()),
                ('brokerage_commission', models.FloatField()),
                ('net_money', models.FloatField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
