# Generated by Django 3.2.13 on 2023-08-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20230803_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='brokerage',
            field=models.CharField(max_length=20),
        ),
    ]
