# Generated by Django 3.2.13 on 2023-08-03 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20230803_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='brokerage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.brokerage'),
        ),
    ]
