# Generated by Django 3.2.13 on 2023-08-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_order_brokerage'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerage',
            name='alias',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
