# Generated by Django 3.2.13 on 2023-08-07 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_auto_20230806_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='currency_primary',
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='brokerage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.brokerage'),
        ),
        migrations.AlterField(
            model_name='order',
            name='brokerage_commission',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_brokerage_account_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
